apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudl-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudl-server
    spec:
      containers:
        - name: cloudl-server
          image: czhablog/cloudl-server:v1
          ports:
            - containerPort: 5000
              name: nodejs-port

  selector:
    matchLabels:
      app: cloudl-server
